baseurl                  = "https://muggle.land"           # Your domain name
languageCode             = "zh-cn"
defaultContentLanguage   = "zh"
isMultilingual           = false
title                    = "Muggle Land"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"
publishDir = "docs"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "shower@MuggleLand"

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Call me Sam"
    # rss                = ""

[[params.mainMenu]]
    link = "https://shower.im"
    text = "Muggle Land"

[imaging]
    quality = 75
